apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: database

spec:
  instances: 2

  imageName: registry.devops.internal:30500/cloudnative-pg/postgresql:18.6-system-trixie
  imagePullPolicy: IfNotPresent

  bootstrap:
    initdb:
      database: app
      owner: app
      dataChecksums: true

  storage:
    storageClass: local-pg
    size: 20Gi

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 2Gi

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required

    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - k8s-worker-01
                  - k8s-worker-02

      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - k8s-worker-01
