---
- name: Update and upgrade Ubuntu servers
  hosts: all
  become: true

  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Upgrade installed packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Remove unused dependencies
      ansible.builtin.apt:
        autoremove: true

    - name: Clean APT cache
      ansible.builtin.apt:
        autoclean: true
